export const ITEM_LIST_REQUEST = 'ITEM_LIST_REQUEST'
export const ITEM_LIST_SUCCESS = 'ITEM_LIST_SUCCESS'
export const ITEM_LIST_FAIL = 'ITEM_LIST_FAIL'

export const ITEM_DETAILS_REQUEST = 'ITEM_DETAILS_REQUEST'
export const ITEM_DETAILS_SUCCESS = 'ITEM_DETAILS_SUCCESS'
export const ITEM_DETAILS_FAIL = 'ITEM_DETAILS_FAIL'

export const ITEM_DELETE_REQUEST = 'ITEM_DELETE_REQUEST'
export const ITEM_DELETE_SUCCESS = 'ITEM_DELETE_SUCCESS'
export const ITEM_DELETE_FAIL = 'ITEM_DELETE_FAIL'

export const ITEM_CREATE_REQUEST = 'ITEM_CREATE_REQUEST'
export const ITEM_CREATE_SUCCESS = 'ITEM_CREATE_SUCCESS'
export const ITEM_CREATE_FAIL = 'ITEM_CREATE_FAIL'
export const ITEM_CREATE_RESET = 'ITEM_CREATE_RESET'

export const ITEM_UPDATE_REQUEST = 'ITEM_UPDATE_REQUEST'
export const ITEM_UPDATE_SUCCESS = 'ITEM_UPDATE_SUCCESS'
export const ITEM_UPDATE_FAIL = 'ITEM_UPDATE_FAIL'
export const ITEM_UPDATE_RESET = 'ITEM_UPDATE_RESET'

export const ITEM_TOP_REQUEST = 'ITEM_TOP_REQUEST'
export const ITEM_TOP_SUCCESS = 'ITEM_TOP_SUCCESS'
export const ITEM_TOP_FAIL = 'ITEM_TOP_FAIL'


export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'

export const CONFIG_LIST_REQUEST = 'CONFIG_LIST_REQUEST'
export const CONFIG_LIST_SUCCESS = 'CONFIG_LIST_SUCCESS'
export const CONFIG_LIST_FAIL = 'CONFIG_LIST_FAIL'