# Generated by Django 3.2.14 on 2023-04-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20230424_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
