# Generated by Django 3.2.14 on 2023-05-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_category_item_idcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
