# Generated by Django 3.2.14 on 2023-05-14 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_category_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('setting', models.CharField(blank=True, max_length=200, null=True)),
                ('settingField', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('instruction', models.CharField(blank=True, max_length=200, null=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('modifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configModifiedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
