# Generated by Django 4.1.5 on 2023-10-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='columnsNumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
